### ISSUE TITLE
Build fails on macOS 15 Sequoia with AttributeError 

### ISSUE THREAD

**Issue by DragonSWDev** [DUOLabs333/vulkan-stream#6]
Does not build on macOS 15.0 Sequoia:

> WARNING: Action download is already completed for dependency asio. Skipping...
WARNING: Action build does not exist for dependency asio! Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency Vulkan_Headers. Skipping...
WARNING: Action build does not exist for dependency Vulkan_Headers! Skipping...
WARNING: Action download is already completed for dependency boost. Skipping...
WARNING: Action build does not exist for dependency boost! Skipping...
Traceback (most recent call last):
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 211, in <module>
    main=import_build(os.getcwd(), external=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 66, in import_build
    mod=import_module_from_file("Buildfile.py", globals_aux = globals())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/tools/utils.py", line 45, in import_module_from_file
    spec.loader.exec_module(mod)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/user/Downloads/stream/vulkan-stream/Buildfile.py", line 20, in <module>
    class main(BuildBase):
  File "/Users/user/Downloads/stream/vulkan-stream/Buildfile.py", line 22, in main
    INCLUDE_PATHS=["autogen","src", get_dep_path("shm_open_anon"), get_dep_path("Vulkan-Headers", "include"), get_dep_path("boost"), conn.library, get_dep_path("Turbo-Base64", ""), get_dep_path("simdjson", "singleheader"), get_dep_path("glaze", "include"), get_dep_path("xxHash-3")]
                                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 56, in get_dep_path
    update.execute_target([dep, {"download", "build"}])
  File "/Users/user/Downloads/stream/tools/update.py", line 36, in execute_target
    formula=getattr(formulas, name)()
            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'DCQVG' has no attribute 'Turbo_Base64'
WARNING: Action build does not exist for dependency asio! Skipping...
WARNING: Action download is already completed for dependency asio. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency Vulkan_Headers! Skipping...
WARNING: Action download is already completed for dependency Vulkan_Headers. Skipping...
WARNING: Action build does not exist for dependency boost! Skipping...
WARNING: Action download is already completed for dependency boost. Skipping...
Traceback (most recent call last):
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 211, in <module>
    main=import_build(os.getcwd(), external=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 66, in import_build
    mod=import_module_from_file("Buildfile.py", globals_aux = globals())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/tools/utils.py", line 45, in import_module_from_file
    spec.loader.exec_module(mod)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/user/Downloads/stream/vulkan-stream/Buildfile.py", line 20, in <module>
    class main(BuildBase):
  File "/Users/user/Downloads/stream/vulkan-stream/Buildfile.py", line 22, in main
    INCLUDE_PATHS=["autogen","src", get_dep_path("shm_open_anon"), get_dep_path("Vulkan-Headers", "include"), get_dep_path("boost"), conn.library, get_dep_path("Turbo-Base64", ""), get_dep_path("simdjson", "singleheader"), get_dep_path("glaze", "include"), get_dep_path("xxHash-3")]
                                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 56, in get_dep_path
    update.execute_target([dep, {"download", "build"}])
  File "/Users/user/Downloads/stream/tools/update.py", line 36, in execute_target
    formula=getattr(formulas, name)()
            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'WRUYH' has no attribute 'Turbo_Base64'
WARNING: Action download is already completed for dependency asio. Skipping...
WARNING: Action build does not exist for dependency asio! Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency Vulkan_Headers. Skipping...
WARNING: Action build does not exist for dependency Vulkan_Headers! Skipping...
WARNING: Action download is already completed for dependency boost. Skipping...
WARNING: Action build does not exist for dependency boost! Skipping...
Traceback (most recent call last):
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 211, in <module>
    main=import_build(os.getcwd(), external=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 66, in import_build
    mod=import_module_from_file("Buildfile.py", globals_aux = globals())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/tools/utils.py", line 45, in import_module_from_file
    spec.loader.exec_module(mod)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/user/Downloads/stream/vulkan-stream/Buildfile.py", line 20, in <module>
    class main(BuildBase):
  File "/Users/user/Downloads/stream/vulkan-stream/Buildfile.py", line 22, in main
    INCLUDE_PATHS=["autogen","src", get_dep_path("shm_open_anon"), get_dep_path("Vulkan-Headers", "include"), get_dep_path("boost"), conn.library, get_dep_path("Turbo-Base64", ""), get_dep_path("simdjson", "singleheader"), get_dep_path("glaze", "include"), get_dep_path("xxHash-3")]
                                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/stream/vulkan-stream/../tools/build.py", line 56, in get_dep_path
    update.execute_target([dep, {"download", "build"}])
  File "/Users/user/Downloads/stream/tools/update.py", line 36, in execute_target
    formula=getattr(formulas, name)()
            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'JCWSG' has no attribute 'Turbo_Base64'

It seems that module name (JCWSG in log) is random as it changes for every build.

**Comment by DUOLabs333** [comment]
Ok, so the problem is that I remove Turbo-Base64 as a dependency (hence the AttributeError), and I have the new version of vulkan-stream locally, but I forgot to push it. I'll do it now.

**Comment by DUOLabs333** [comment]
Try again now (I had to do a force-push, which is why my git-push cron wasn't work) --- you may have to `git reset --hard`.

**Comment by DragonSWDev** [comment]
I did fresh git clone to be sure and it still doesn't build. This time it fails because it couldn't find lz4.h:

> asio_c.cpp:8:10: fatal error: 'lz4.h' file not found

I also noticed that it cannot find vk.xml file:

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Downloads/tools/external/Vulkan-Headers/registry/vk.xml'

Second error is probably just a typo somewhere in the build script, as it tries to reach tools/external/Vulkan-Headers directory that doesn't exist however there is directory there called Vulkan_Headers (underscore instead of hyphen). After I copied this directory and renamed it to Vulkan-Headers this error is gone. No idea about lz4.h, I have it installed with brew.

**Comment by DUOLabs333** [comment]
> Second error is probably just a typo somewhere in the build script

Yeah, this is because the build script replaces all dashes with underscores --- I'll update that (thanks by the way, for being willing to work through setting up the project).

> asio_c.cpp:8:10: fatal error: 'lz4.h' file not found

I'm not sure why this is happening (by the way, you shouldn't need to install lz4, since we download and build our own copy) --- I'll look into that.

**Comment by DragonSWDev** [comment]
I noticed that not all needed dependencies are downloaded. lz4, simdutf and xxHash_3 directories are empty in tools/external. This is likely why it cannot find those during build.

**Comment by DUOLabs333** [comment]
Ah, that makes sense --- delete those directories, pull the tools repo (I pushed a fix so that the script no longer changes the name of the directories to match the Python class name), and try again.

**Comment by DragonSWDev** [comment]
That fixes Vulkan-Headers error, however lz4 error is still present and those directories are still empty.

**Comment by DragonSWDev** [comment]
After I removed these directories it started working (no idea why as I pulled your changes), now these directories have content and build completes but vulkan_stream binary fails to run with following error:

> Library not loaded: @rpath/libvulkan.1.dylib

In build log I noticed ld warning:

> ld: warning: search path '/Users/user/.nix-profile/Library/Frameworks' not found

I guess it tries to find Vulkan framework in different location than it is installed on my system.

**Comment by DUOLabs333** [comment]
Did you install the Vulkan loader?

**Comment by DragonSWDev** [comment]
@DUOLabs333 I installed Vulkan with official Vulkan SDK installer and vulkan_loader with brew. Am I missing something else?

**Comment by DUOLabs333** [comment]
What version of gcc/clang are you using?

**Comment by DragonSWDev** [comment]
clang --version:

> Apple clang version 16.0.0 (clang-1600.0.26.3)

**Comment by DUOLabs333** [comment]
Hmmm.... that should be fine. Can you post the result of `otool -L ./vulkan_stream`?

**Comment by DragonSWDev** [comment]
> ./vulkan_stream:
> 	@rpath/libvulkan.1.dylib (compatibility version 1.0.0, current version 1.3.0)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1800.101.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1351.0.0)

**Comment by DragonSWDev** [comment]
I've managed to make vulkan_stream binary work (or at least run without any errors as I didn't try running Vulkan application on Linux guest) after using install_name_tool to change @rpath/libvulkan.1.dylib to the location of libvulkan.1.dylib in the Vulkan SDK install directory. Since Vulkan SDK can be installed in any directory, that probably should be configured somewhere before build.

**Comment by DUOLabs333** [comment]
> install_name_tool to change @rpath/libvulkan.1.dylib to the location of libvulkan.1.dylib in the Vulkan SDK install directory.

This shouldn't be needed though --- can you install vkcube and run `otool -L $(which vkcube)`? The rpath should not be involved at all.

**Comment by DragonSWDev** [comment]
vkcube installed by homebrew is shell script that opens /opt/homebrew/Cellar/vulkan-tools/1.3.295/cube/vkcube.app. This app however doesn't work as it fails to find VK_KHR_surface. Here is otool output for binary:

```
vkcube:
	/opt/homebrew/opt/vulkan-loader/lib/libvulkan.1.dylib (compatibility version 1.0.0, current version 1.3.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 24.0.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1351.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2566.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 3038.1.255)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 3038.1.255)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

Vulkan SDK installer installs its own version of vkcube.app and this one works without issues. otool output:

```
vkcubepp (architecture x86_64):
	@rpath/libvulkan.1.dylib (compatibility version 1.0.0, current version 1.3.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 24.0.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1700.255.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2487.60.105)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2503.1.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 2503.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
vkcubepp (architecture arm64):
	@rpath/libvulkan.1.dylib (compatibility version 1.0.0, current version 1.3.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 24.0.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1700.255.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2487.60.105)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2503.1.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 2503.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

I guess rpath should point to the location where Vulkan loader is present but I'm not sure how to setup it properly during build, I'm not very experienced with developing software for macOS.

**Comment by DUOLabs333** [comment]
Yes, it seems that vulkan_stream is picking up the the vulkan-loader from the SDK, not from homebrew. `libvulkan.dylib` in this case seems to be a "link" to `@rpath/libvulkan.1.dylib`. The "proper" solution here should be to uninstall the SDK, and only rely on Homebrew. However, as a workaround, do `DYLD_LIBRARY_PATH=<path to vulkan sdk> ./vulkan_stream` (From [here](https://vulkan.lunarg.com/doc/sdk/1.3.290.0/mac/getting_started.html), it seems to be that recent version of macOS no longer automatically adds `/usr/local` to the rpath automatically. This would also explain why I never faced this --- I'm on macOS 11).

If that works, I'll add support to optionally add the SDK path to the rpath.

**Comment by DragonSWDev** [comment]
So basically it builds on both macOS and Linux (Fedora 41). On macOS side lz4 error still sometimes occurs but that might be something with my Internet as removing it and running build again downloads it properly and build progresses further. vulkan_stream executable works with DYLD_LIBRARY_PATH pointing to the lib directory in Vulkan SDK installation. It builds without issues on Linux.

Running Vulkan applications on Linux fails with this error:
`ERROR: [Loader Message] Code 0 : ././vulkan_stream.so: undefined symbol: vkGetPhysicalDeviceXcbPresentationSupportKHR`

I'm not sure if this is part of this issue or I should create another issue for that.

It seems that Vulkan is loaded dynamically and for some reason it couldn't find Vulkan loader. On Fedora Vulkan libraries are present in the /usr/lib64 directory. Exporting LD_LIBRARY_PATH didn't help.

**Comment by DUOLabs333** [comment]
>  vulkan_stream executable works with DYLD_LIBRARY_PATH pointing to the lib directory in Vulkan SDK installation

Great! I'll update the Buildfile to add an option for `VULKAN_SDK`, and update the README. Can you tell me the exact path of `libvulkan.1.dylib` on your installation?


> Running Vulkan applications on Linux fails with this error:
ERROR: [Loader Message] Code 0 : ././vulkan_stream.so: undefined symbol: vkGetPhysicalDeviceXcbPresentationSupportKHR

This should probably be a separate issue (but keep this one open so I don't forget about it). Yeah, due to an issue I had with another program, I had to hide all of the symbols in the library. This means that a loader is required for it to work. I didn't really like this, but the alternative workaround was too messy, so this was the better of two evils.

**Comment by DragonSWDev** [comment]
When I forced loading Vulkan library with LD_PRELOAD I actually managed to fix undefined symbols errors, however Vulkan applications still don't work. I'll create separate issue for that.

**Comment by DUOLabs333** [comment]
I've committed a fix for this (it has not been pushed yet). Thanks for walking me through this!

**Comment by DUOLabs333** [comment]
The fix has now been pushed.
